FROM php:7.4-fpm

# RUN apt-get update && apt-get install -y \
#     curl \
#     wget \
#     git \
#     libfreetype6-dev \
#     libjpeg62-turbo-dev \
#     libxslt-dev \
#     libicu-dev \
#     libmcrypt-dev \
#     libpng12-dev \
#     libxml2-dev

WORKDIR /app

CMD ["php-fpm"]