version: "3.3"
services:
  nginx:
    container_name: nginx_container
    build:
      context: ./docker/nginxServer
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./docker/nginxServer/config/sites-available:/etc/nginx/sites-available
      - ./docker/nginxServer/config/sites-available:/etc/nginx/sites-enabled
      - ./docker/nginxServer/config/nginx.conf:/etc/nginx/nginx.conf
      - "./apps:/apps"
      - ./docker/nginxServer/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker_net:
        ipv4_address: 172.29.1.1

  php:
    container_name: php-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - "./apps:/apps"
    networks:
      docker_net:
        ipv4_address: 172.29.1.2

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
    networks:
      docker_net:
        ipv4_address: 172.29.1.3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      docker_net:
        ipv4_address: 172.29.1.4

networks:
  docker_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
