version: "3.3"
services:
  nginx:
    container_name: nginx_container
    build:
      context: ./docker/nginxServer
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./docker/nginxServer/config/sites-available:/etc/nginx/sites-available
      - ./docker/nginxServer/config/sites-available:/etc/nginx/sites-enabled
      - ./docker/nginxServer/config/nginx.conf:/etc/nginx/nginx.conf
      - "./app:/app"
      - ./docker/nginxServer/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker_net:
        ipv4_address: 172.28.1.1
  php:
    container_name: php-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    networks:
      docker_net:
        ipv4_address: 172.28.1.2
networks:
  docker_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
